### ISSUE TITLE
SharedHashMap interface signatures 

### ISSUE THREAD

**Issue by Cotton-Ben** [peter-lawrey/HugeCollections-OLD#14]
Do you think it might be a little clearer if the

```
 V acquireUsing(Object key, V value);
```

signature was changed to

```
 V getOrCreate(Object key, V value);  //makes it more obvious non-NULL will be returned.
```

or possibly

```
V getNonNull(Object key, V value);     //makes it totally obvious non-NULL will be returned.
```

?

Keeping the current signature is fine, of course,  I'm just saying for ( simple minded ) me the last one makes it easier to remember which signature can't return NULL.  ;-)

**Comment by Cotton-Ben** [comment]
```
 V getNonNullUsing(Object key, V value);     //even better?
```

**Comment by Cotton-Ben** [comment]
I change me mind!  I'm now familar with ...

```
V acquireUsing(Object key, V value);
```

let's keep it.

**Comment by peter-lawrey** [comment]
While not universally in computing, it think it is clear enough. I have
seen "acquire" used quite a few time.

http://www.oxforddictionaries.com/definition/english/acquire

"acquire [verb] buy or obtain (an asset or object) for oneself."

For me,

newXxxx => create a new thing always
getXxxx => get if present.
acquireXxxx => get if present or create if not.

**Comment by RobAustin** [comment]
I was struggling to understand what acquireUsing() does, for me getOrCreate() is much clearer.

Rob

**Comment by peter-lawrey** [comment]
The problem is that it doesn't strictly create anything either.
acquireUsing doesn't create any objects when used correctly, it is more
like assigned-to-existing-record-or-allocate-a-new-record-and-assign-it.

**Comment by Cotton-Ben** [comment]
I thought so too at first, but on second thought ... 'acquire' feels 
more regal.

**Comment by RobAustin** [comment]
Some good java doc will help, Peter if you email me an explanation, I’ll add it to the code.

Rob

**Comment by peter-lawrey** [comment]
What you could do is treat remove(K, V) as replace(K,V, null) where the
replaced value of null implies a delete.

**Comment by peter-lawrey** [comment]
Do you think it makes sense to have a replaceReturnsNull(true) flag?

**Comment by RobAustin** [comment]
Ok

**Comment by peter-lawrey** [comment]
Could you do a review of the methods implemented by AbstractMap to see
which ones we might want to override?

**Comment by RobAustin** [comment]
No - as before you do the replace you have to read() to see if a value exists so you do the read anyway.

**Comment by RobAustin** [comment]
Sure - I'll raise some Jira's.

**Comment by peter-lawrey** [comment]
Just for the record, acquireUsing, doesn't create any objects or use any
extra memory unless you pass null.

**Comment by Cotton-Ben** [comment]
Absolutely.  I can see it being empowering ....

**Comment by RobAustin** [comment]
These methods although similar, are not identical, I will refactor out the commonalities though

**Comment by peter-lawrey** [comment]
Refactoring is a nice to have for the alpha release, we should go back and
refactor for the beta release.

**Comment by RobAustin** [comment]
Ok - I'll focus on more important tasks for the moment.

**Comment by leventov** [comment]
Don't forget about IDE autocomplete. If I forget `acquireUsing` method name (that's easy), I want to type "map.get", then Ctrl+Enter to see all kinds of `get` available. Simple `get` creates an object as well in sense we mean when consider `getOrCreate` name for `acquireUsing`, thus I'd suggest `getOrReuse`.

**Comment by RobAustin** [comment]
I agree

**Comment by peter-lawrey** [comment]
getUsing will always reuse, not "get OR reuse".  acquireUsing will also
always reuse.  The difference is that acquire will never return null.

**Comment by leventov** [comment]
`getUsingOrCreate`

**Comment by Cotton-Ben** [comment]
We also initially felt awkward with the choice "acquireUsing" ... but 
that awkwardness truly wore off (and in very little time).  We made the 
gentle effort= "let us try to adapt to its name" rather than "let it 
adapt to our name".  For us it worked.  "acquire' is a richer, more 
regal verb.  As Peter points out, it overloads in-place full 
"getOrCreate" semantics (without the need of a literal in-order binary 
conjunctive).  It took all of a 2 minutes of our practicing "you can 
'get' a NULL"  but you can't "acquire" a NULL.  By the third minute, we 
were in love with "acquireUsing" ... so much so that we closed #13.

**Comment by leventov** [comment]
OK, you convinced me.

**Comment by peter-lawrey** [comment]
get() creates an object.

acquireUsing(key, non-null) and getUsing(key, non-null) never create an
object or use more memory.

I think it would be confusing to put "Create" on the method which doesn't
create, while the method called just get() does create.
