### ISSUE TITLE
setSegments(int) is not public in HugeConfig; cannot be accessed from outside package

### ISSUE THREAD

**Issue by gilfernandes** [peter-lawrey/HugeCollections-OLD#20]
Hello,

I was just playing around with the examples and I got surprised by this error message on this code:

``` java
package com.onepointltd.file.operations;

...

@Test
    public void testHugeMap() {
        HugeConfig config = HugeConfig.DEFAULT.clone()
                .setSegments(128)
                .setSmallEntrySize(128)
                .setCapacity(10000);
    }
```

I get these error messages:

setSegments(int) is not public in HugeConfig; cannot be accessed from outside package

setSmallEntrySize(int) is not public in HugeConfig; cannot be accessed from outside package

setCapacity(int) is not public in HugeConfig; cannot be accessed from outside package

My current maven dependency is:

``` xml
<dependency>
            <groupId>net.openhft</groupId>
            <artifactId>collections-sandbox</artifactId>
            <version>3.0.3-SNAPSHOT</version>
            <type>jar</type>
        </dependency>
```

If this is really a stupid question, please bare with me. I am just a beginner using OpenHFT.

Best regards,

Gil

**Comment by peter-lawrey** [comment]
This is an oversight. I will fix this today.

**Comment by RobAustin** [comment]
Gil

Thanks for your feedback, we will definatly make the change that you suggest but I recommend you don’t use the code in collections-sandbox, Its’ our beta development area and contains work that is in progress. Its much better to use.

<dependency>
    <groupId>net.openhft</groupId>
    <artifactId>collections</artifactId>
    <version>3.0.2</version>
</dependency>

having said that, I think your comment about the visibility of these methods is an over site and we will correct this in the next release.

Rob

**Comment by gilfernandes** [comment]
Hello, Rob,

I have tried:

``` bash
git clone --branch collections-3.0.2 https://github.com/OpenHFT/HugeCollections.git
```

and 

``` bash
mvn clean install
```

Then I changed the dependency to:

``` xml
<dependency>
            <groupId>net.openhft</groupId>
            <artifactId>collections</artifactId>
            <version>3.0.2</version>
        </dependency>
```

but the problem persists. 

In the source code of HugeConfig I find:

``` java
HugeConfig setSmallEntrySize(int smallEntrySize) {
        this.smallEntrySize = Maths.nextPower2(smallEntrySize, 64);
        return this;
    }

...

HugeConfig setSegments(int segments) {
        this.segments = Maths.nextPower2(segments, 16);
        return this;
    }
```

And this code suggests that the setter methods are package protected.

But anyway I can use the collection, if I use only:

``` java
HugeConfig config = HugeConfig.DEFAULT.clone();
```

Anyway: I like your project very much and really appreciate your excellent work.

best regards,

Gil
