### ISSUE TITLE
OpenHFT scope of capability re: SHMEntry fields (user JBI supplied) and "barrier" operations

### ISSUE THREAD

**Issue by Cotton-Ben** [peter-lawrey/HugeCollections-OLD#40]
what is the currently supported scope of SHMEntry filed barrier operations (across both Threads and PIDs)?

E.g.  If I supply a JBI entry of 

```
<T>  MyField;
```

and signatures

```


<T> getMyField();
void setMyField(<T> myField);

boolean compareAndSwapMyField(<T>  expected, <T> value);
<T> getVolatileMyField()
void setOrderedMyField(<T> myField);


```

should we expect that the run-time OpenHFT generated SHMEntry impl class will provide the capability such that the first 2 methods above are non-barrier crossing impls and that last 3 methods are guaranteed to be barrier crossing impls?

is all of this supported currently?

**Comment by Cotton-Ben** [comment]
Also what is the currently supported type domain set (all primitives + String?) for <T> for this issue?

**Comment by peter-lawrey** [comment]
you are right however there is addXxxx and addAtomicXxxx.  for a complete
list of supported options see

https://github.com/OpenHFT/Java-Lang/tree/master/lang/src/main/java/net/openhft/lang/values

**Comment by Cotton-Ben** [comment]
How high an OpenHFT dev  priority "TODO" list is it to support end-users supplying signatures like

```
<T> getVolatileMyField()
void setOrderedMyField(<T> myField);
```

in their  JBI interfaces (to be passed to net.openhft.lang.model.DataValueClasses API)?

Would it be reasonable to ask that this be supported by EOY 2014?

**Comment by peter-lawrey** [comment]
Can you check these are not there already?

Obviously we would like you to be one of our paying customers and you will
get priority support and extension.

**Comment by Cotton-Ben** [comment]
> Can you check these are not there already?

Oh wow.  Checking right now ....

> Obviously we would like you to be one of our paying customers and you will
> get priority support and extension.

Coming soon!

**Comment by peter-lawrey** [comment]
https://github.com/OpenHFT/Java-Lang/blob/master/lang/src/main/java/net/openhft/lang/values/DoubleValue.java

**Comment by Cotton-Ben** [comment]
sweet.

**Comment by Frank-Bradley** [comment]
Forgive me for re-opening this issue ... but I have 1 important question:

Does the support of OpenHFT volatile signatures

```
<T> getVolatileMyField()
void setOrderedMyField(<T> myField);
```

(in user supplied JBIs) imply that OpenHFT will do for the r/w ordering (of these kind of fields) across PIDs -- the exact  kind of "order bookeeping" that the  default Java volatile does (for these kind of fields) across Threads?

**Comment by peter-lawrey** [comment]
Yes. It provides the appropriate read/write memory barriers.
